#!/bin/sh

# PROVIDE: stepsboi
# REQUIRE: LOGIN FILESYSTEMS
# KEYWORD: shutdown

. /etc/rc.subr  # has functions for an rc.d script to use

name="stepsboi"     # defines the name of our script
# Required so that rc.d can match the PID and the process name:
# https://forums.freebsd.org/threads/rc-d-doesnt-see-my-pidfile.69141/
procname="/bin/sh"
desc="stepsboi"
rcvar="${name}_enable"  # ON/OFF knob variable
pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon" # if set, rc.subr will act according to the scenario of serving a conventional daemon, default methods will be provided for such arguments: start, stop, restart
command_args="-o /var/log/stepsboi.log -p ${pidfile} -- ${procname} /root/run.sh"

load_rc_config $name    # load rc.conf
run_rc_command "$@"     # usually the last command, invokes rc.subr machinery